version: "3.2"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
    ports:
    - target: ${APP_PORT:-3000}
    environment:
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB: ${DB}
      NODE_ENV: production
  test:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test:mocha" ]
    depends_on:
    - app
    - db
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB: ${DB}
      NODE_ENV: development
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}