name: Sample movies API workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests
    env:
      TEST_COMPOSE_FILE: docker-compose.test.yml
      ENV_FILE: .env.dev.example
      API_KEY: ${{ secrets.API_KEY }}
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: password
      DB_HOST: db
      DB: movies
      JWT_SECRET: secret
      APP_PORT: 3000
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f $TEST_COMPOSE_FILE run test
